---
title: "Michigan COVID Data"
author: "Adam D. DenHaan"
date: "`r format(Sys.time(), '%b %d, %Y')`"
output: github_document
---

```{r setup, include=FALSE}
# R Setup
knitr::opts_chunk$set(echo = TRUE, fig.path = "MiCorona_files/figure-gfm/")
library(dplyr)
library(rlang)
library(ggplot2)
library(lubridate)
library(gginnards)
library(patchwork)

# Python Setup
library(reticulate)
if (!py_module_available("bs4")) py_install("bs4")
if (!py_module_available("urllib")) py_install("urllib")
if (!py_module_available("pandas")) py_install("pandas")
if (!py_module_available("datetime")) py_install("datetime")
if (!py_module_available("openpyxl")) py_install("openpyxl")
py_run_string("import pandas as pd; pd.options.display.max_columns = None")
```

Get link for data:
```{python get-excel-link, results='hide'}
from bs4 import BeautifulSoup
from urllib.request import urlopen
from datetime import datetime, timedelta


# Get data into pandas df
url = "https://www.michigan.gov/coronavirus/0,9753,7-406-98163_98173---,00.html"

html = urlopen(url).read().decode("utf-8")

soup = BeautifulSoup(html, features="html.parser")
links = [link.get('href') for link in soup.find_all('a')]

# find the link that has "by_Date" in it
for link in links:
    if isinstance(link, str) and "Cases-and-Deaths-by-County-and-by-Date-of-Symptom" in link:
        break
finallink = f"https://michigan.gov{link}"
```

Download data:
```{r get-excel}
temp <- tempfile()
download.file(py$finallink, destfile = temp)
mi_data = readxl::read_excel(temp)
```

Clean data:
```{python aggregate-data}
mi_data = r.mi_data
mi_data.head()

max_date = max(mi_data["Updated"])

agg_data = mi_data.groupby(["Date"], as_index=False).sum()

diff = datetime.now() - timedelta(7)
  
mi_cases_by_day_last4 = agg_data[agg_data["Date"] > diff]
agg_data = agg_data[agg_data["Date"] <= diff]
```

```{r data-load}
mi_cases_by_day_exclusive = py$agg_data
date_update = format(py$max_date, '%d %b %Y')
mi_cases_by_day_last4 = py$mi_cases_by_day_last4
```

Visualization:
```{r viz_function}
ma <- function(x, n = 7){stats::filter(x, rep(1 / n, n), sides = 2)}

viz_function <- function(df, df2, x, y, vertline = TRUE, log = FALSE) {
  
  if (log) {
    df  <- df  %>% mutate(y = log10({{y}}))
    df2 <- df2 %>% mutate(y = log10({{y}}))
    y_lbl = paste(deparse(substitute(y)), "(log10)")
  } else {
    df  <- df  %>% mutate(y = {{y}})
    df2 <- df2 %>% mutate(y = {{y}})
    y_lbl = deparse(substitute(y))
  }
  
  # Moving average
  avg = ma(df["y"])
  df = bind_cols(df, avg = avg)
  
  plot <- ggplot(data = df, mapping = aes(x = as.Date({{x}}), y = y)) +
    ylim(c(0,NA)) +
    geom_point(alpha = .5) +
    geom_line(y = avg, color = "blue") +
    geom_point(
      data = df2,
      mapping = aes(x = as.Date({{x}}), y = y, color = "red")
    ) +
    scale_x_date(date_labels = "%m-%y", date_breaks = "2 months") + 
    theme(legend.position = "none") +
    labs(
      title = paste("Michigan Coronavirus", deparse(substitute(y)), "updated", date_update),
      subtitle = "With 7 day moving average",
      x = deparse(substitute(x)),
      y = y_lbl
    )
  
  if (vertline) {
    plot <- append_layers(
      plot,
      geom_vline(xintercept = today() - 28, color = "orange"),
      position = "bottom"
    )
  }
  plot
}
```

```{r viz, fig.height=7, dpi=300, warning=FALSE}
viz_function(mi_cases_by_day_exclusive, mi_cases_by_day_last4, Date, Cases, vertline = FALSE) /
  viz_function(mi_cases_by_day_exclusive, mi_cases_by_day_last4, Date, Cases, log = TRUE, vertline = FALSE)
```

```{r viz2, fig.height=7, dpi=300, warning=FALSE}
viz_function(mi_cases_by_day_exclusive, mi_cases_by_day_last4, Date, Deaths, vertline = FALSE) / 
  viz_function(mi_cases_by_day_exclusive, mi_cases_by_day_last4, Date, Deaths, vertline = FALSE, log = TRUE)
```

Note that the last `r length(unique(mi_cases_by_day_last4$Date))` days of data have been colored red on the graph, as they frequently change as more information becomes available. 
